name: di
description: A new Flutter package project.
version: 0.0.1
# homepage:

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  data:
    path: ../data
  domain:
    path: ../domain
  get_it:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0